name: whr
version: "0.0.3"
slug: whr
description: whr
url: "https://github.com/SvenHamers/whr_930"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  username: "user"
  password: "password"
  ip: "home assistant ip adress"
  usb_device: "/dev/ttyUSB0"
schema:
  username: "str"
  password: "str"
  ip: "str"
  usb_device: "str"

image: "svenhamers1992/whr"